export const DISCOVER_MOVIES = 'DISCOVER_MOVIES';
export const DISCOVER_MOVIES_REQUEST = 'DISCOVER_MOVIES_REQUEST';
export const DISCOVER_MOVIES_SUCCESS = 'DISCOVER_MOVIES_SUCCESS';
export const DISCOVER_MOVIES_FAILURE = 'DISCOVER_MOVIES_FAILURE';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

export const GET_GENRES = 'GET_GENRES';
export const GET_GENRES_REQUEST = 'GET_GENRES_REQUEST';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAILURE = 'GET_GENRES_FAILURE';

export const FILTER_MOVIES_BY_RATING = 'FILTER_MOVIES_BY_RATING';
export const FILTER_MOVIES_BY_RATING_FINISHED = 'FILTER_MOVIES_BY_RATING_FINISHED';
